import { ProjectsData } from '@/shared/lib/types';

export const projectsData: ProjectsData = [
  {
    title: 'Food Delivery',
    image: '/portfolio/images/7-food-delivery-min.jpg',
    hrefSite: 'https://next-food-delivery-indol.vercel.app',
    hrefGit: 'https://github.com/oleg-kuzmin/next-food-delivery',
    description:
      'E-commerce веб-приложение на React (Next.js) - сервис доставки еды (5 страниц: главная, корзина, форма, условия доставки, акции). Внешнее api (dadata.ru) для получения адреса.',
    functional: [
      'Поиск адреса доставки.',
      'Добавление, изменение, удаление товаров из корзины.',
      'Отображение количества товаров и общей стоимости.',
      'Подсчет минимальной и общей стоимости доставки.',
      'Заполнение формы заказа, кастомная валидация формы.',
      'Сохранение данных через Redux.',
      'Модальные окна (пустая корзина, условия на странице формы).',
      'Аккордеон на странице условий доставки.',
    ],
    technologies: [
      'Адаптивная верстка Perfect Pixel по макету Figma от 320px.',
      'Проект полностью на React, Redux Toolkit.',
      'Препроцессор Sass.',
      'Модули scss для React.',
      'Cовременный роутинг от Next (App Router).',
      'Api для поиска адреса доставки (dadata.ru).',
      'Аккордеон на странице условий доставки на чистом CSS.',
      'Библиотека Swiper с настройками под разные устройства.',
      'Библиотека React Transition Group для анимации.',
    ],
  },
  {
    title: 'Lead Conveer',
    image: '/portfolio/images/8-leadconveer-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/leadconveer',
    hrefGit: 'https://github.com/oleg-kuzmin/leadconveer',
    description: 'Сайт-лэндинг на React+Typescript (Next.js) - создание лидов для бизнеса.',
    functional: [
      'Слайдер с отображением кликабельной пагинации.',
      'Модальное окно с навигацией в мобильной версии.',
      'Воспроизведение видео-роликов.',
      'Аккордеон с независимыми друг от друга панелями.',
    ],
    technologies: [
      'Адаптивная верстка Perfect Pixel по макету Figma от 320px.',
      'FSD-архитектура проекта.',
      'Препроцессор Sass.',
      'Модули scss для React.',
      'React + Next.js.',
      'Используется Typescript.',
      'Библиотеки swiper.js, classnames.',
    ],
  },
  {
    title: 'Doors Locks (в разработке)',
    image: '/portfolio/images/9-door-locks-min.jpg',
    hrefSite: 'https://door-locks-vite.vercel.app',
    hrefGit: 'https://github.com/oleg-kuzmin/door-locks-vite',
    description: 'E-commerce веб-приложение на React+Typescript (Vite) - магазин дверных замков.',
    functional: ['Слайдер с отображением пагинации и стрелок.', 'Автоматические переключение слайдов.', '...'],
    technologies: [
      'FSD-архитектура проекта.',
      'Библиотеки swiper.js, react-transition-group.',
      'Используется Typescript.',
      '...',
    ],
  },
  {
    title: 'Colors',
    image: '/portfolio/images/6-colors-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/colors',
    hrefGit: 'https://github.com/oleg-kuzmin/colors',
    description:
      'E-commerce веб-приложение на JavaScript и Pug (Webpack) - магазин красок. Внешнее api (mockapi.io) для получения данных.',
    functional: [
      'Слайдер с отображением пагинации и стрелок.',
      'Фильтрация по типам товаров.',
      'Сортировка по убыванию и возрастанию цены.',
      'Добавление товара в корзину.',
      'Изменение количества товаров в корзине.',
      'Расчет стоимости товаров в корзине.',
      'Удаление товара из корзины.',
      'Открытие и закрытие модального окна с корзиной.',
    ],
    technologies: [
      'Семантическая структура html.',
      'Шаблонизатор Pug.',
      'Адаптивная верстка Perfect Pixel по макету Figma.',
      'Структура файлов, наименование классов в стиле BEM.',
      'Препроцессор Sass.',
      'Логика взаимодействия на JavaScript + библиотека Swiper.',
      'Загрузка данных с внешнего api (mockapi.io).',
    ],
  },
  {
    title: 'Frontend Cats',
    image: '/portfolio/images/5-frontend-cats-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/frontend-challenge',
    hrefGit: 'https://github.com/oleg-kuzmin/frontend-challenge',
    description:
      'Веб-приложение на React+Typescript (Vite) - бесконечные картинки котиков. Внешнее api (thecatapi.com) для получения данных.',
    functional: [
      'Добавление в избранное и сохранение на клиенте.',
      'Просмотр избранного.',
      'Загрузка новой порции картинок при нажатии на кнопку.',
      'Бесконечный скролл с загрузкой данных.',
      'Многофункциональная кнопка взаимодействия с api.',
      'Отображение заглушки скелетон при загрузке картинки.',
    ],
    technologies: [
      'Адаптивная верстка Perfect Pixel от 320px.',
      'Препроцессор Sass.',
      'Модули scss для React.',
      'Загрузка данных с внешнего api (thecatapi.com).',
      'Обработка ошибок и процесса загрузки данных.',
      'Используется Typescript.',
    ],
  },
  {
    title: 'Mesto Project',
    image: '/portfolio/images/4-mesto-project-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/mesto-project',
    hrefGit: 'https://github.com/oleg-kuzmin/mesto-project',
    description:
      'Веб-приложение JavaScript на классах ООП (Webpack) - общая галерея фотографий красивых мест от разных пользователей с возможностью получения, добавления, удаления, изменения фото. Используется внешнее api (api.nomoreparties.co).',
    functional: [
      'Получение карточек, данных пользователя с сервера.',
      'Добавление и удаление своих карточек. Чужие удалить нельзя.',
      'Добавление своих лайков и учет количества общих лайков.',
      'Изменение данных пользователя.',
      'Модальные окна (карточки, пользователь, нажатие на карточку).',
      'Кастомная валидация формы.',
      'Данные удаляются, изменяются, сохраняются на сервере.',
    ],
    technologies: [
      'Семантическая структура html.',
      'Адаптивная верстка Perfect Pixel по макету Figma от 320px.',
      'Структура файлов, наименование классов в стиле BEM.',
      'Архитектура приложения через классы ООП.',
      'Препроцессор Sass.',
      'Сборка проекта через Webpack.',
      'Библиотеки Babel, Autoprefixer, Postcss, cssnano, Gh-pages.',
      'REST api (get, post, delete, patch, put) для изменения данных.',
    ],
  },
  {
    title: 'Film Camera Repair',
    image: '/portfolio/images/3-film-camera-repair-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/film-camera-repair',
    hrefGit: 'https://github.com/oleg-kuzmin/film-camera-repair',
    description: 'Сайт-лэндинг по ремонту фотоаппаратов.',
    functional: ['Ввод почты и отправка формы.'],
    technologies: [
      'Семантическая структура html.',
      'Адаптивная верстка Perfect Pixel по макету Figma от 320px.',
      'Структура файлов, наименование классов в стиле BEM.',
      'Препроцессор Sass.',
      'Используется Flex.',
    ],
  },
  {
    title: 'Russian Travel',
    image: '/portfolio/images/2-russian-travel-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/russian-travel',
    hrefGit: 'https://github.com/oleg-kuzmin/russian-travel',
    description: 'Сайт-лэндинг про путешествия.',
    functional: [],
    technologies: [
      'Семантическая структура html.',
      'Адаптивная верстка Perfect Pixel по макету Figma от 320px.',
      'Структура файлов, наименование классов в стиле BEM.',
      'Используется Flex, Grid.',
      'Несколько слоев фона.',
    ],
  },
  {
    title: 'How To Learn',
    image: '/portfolio/images/1-how-to-learn-min.jpg',
    hrefSite: 'https://oleg-kuzmin.github.io/how-to-learn',
    hrefGit: 'https://github.com/oleg-kuzmin/how-to-learn',
    description: 'Учебный сайт-лэндинг от Яндекс.',
    functional: [],
    technologies: [
      'Семантическая структура html.',
      'Структура файлов, наименование классов в стиле BEM.',
      'Используется Flex.',
      'Несколько слоев фона.',
      'Используются CSS анимации.',
    ],
  },
];
